### ISSUE TITLE
Todo Feature

### ISSUE THREAD

**Issue by echosoar** [echosoar/jsi#7]
- [x] Base(String/Number/Boolean/Object/Array/Function/Error) Object
   - [ ] string.pro.charAt
   - [ ] string.pro.charCodeAt
- [x] new Object
- [x] arrow function
- [ ] new function
- [ ] this
- [ ] instanceof
- [ ] deconstructed assignment
- [x] try-catch
  - [ ] finally
- [x] typeof
- [x] throw error / global error
- [ ] eval
- [ ] class
- 
- [ ] This
- [ ] float
- [ ] Numeric separators [ES2021]
- [x] TC39 test262
- [ ] promise
- [ ] Iterators / for -in/for-of
- [ ] more global Object
  - [ ] Regexp
  - [ ] Symbol
  - [ ] Bigint
  - [ ] Map
  - [ ] Set
  - [ ] Math
  - [ ] Date
  - [ ] JSON
- [ ] microtask queue for timer and promise
